// <auto-generated />
using BakeryRazorPage.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BakeryRazorPage.Migrations
{
    [DbContext(typeof(BakeryContext))]
    [Migration("20191101043103_UpdatedModelBuilder")]
    partial class UpdatedModelBuilder
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0");

            modelBuilder.Entity("BakeryRazorPage.Models.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageName")
                        .HasColumnName("ImageFileName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Description = "For those who need more than a little pick-me-up",
                            ImageName = "bigolcup.jpg",
                            Name = "Big Ol' Cuppa",
                            Price = 8.99m
                        },
                        new
                        {
                            ID = 2,
                            Description = "In case you need to cut back a little",
                            ImageName = "smallolcup.jpg",
                            Name = "Tiny Ol' Cuppa",
                            Price = 4.99m
                        },
                        new
                        {
                            ID = 3,
                            Description = "What the!? How did this get here?",
                            ImageName = "agun.jpg",
                            Name = "Literally a Big Gun",
                            Price = 999.99m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
